export default [
  "algorithm",
  "array",
  "boolean",
  "bug",
  "class",
  "code",
  "compiler",
  "data",
  "database",
  "debug",
  "function",
  "if-else",
  "integer",
  "loop",
  "object",
  "print",
  "program",
  "string",
  "variable",
  "while",
  "javascript",
  "python",
  "java",
  "html",
  "css",
  "react",
  "angular",
  "vue",
  "node.js",
  "git",
  "github",
  "vscode",
  "intellij",
  "terminal",
  "console",
  "syntax",
  "error",
  "exception",
  "library",
  "framework",
  "api",
  "web",
  "mobile",
  "desktop",
  "frontend",
  "backend",
  "fullstack",
  "debugging",
  "testing",
  "unit test",
  "integration test",
  "continuous integration",
  "deployment",
  "hosting",
  "server",
  "client",
  "network",
  "internet",
  "domain",
  "hosting",
  "database",
  "sql",
  "nosql",
  "mongodb",
  "mysql",
  "postgresql",
  "oracle",
  "cloud",
  "aws",
  "gcp",
  "azure",
  "docker",
  "kubernetes",
  "devops",
  "agile",
  "scrum",
  "kanban",
  "design pattern",
  "object-oriented programming",
  "functional programming",
  "paradigm",
  "abstraction",
  "encapsulation",
  "inheritance",
  "polymorphism",
  "interface",
  "generics",
  "lambda",
  "recursion",
  "dynamic typing",
  "static typing",
  "type system",
  "garbage collection",
  "memory management",
  "pointer",
  "reference",
  "scope",
  "closure",
  "module",
  "package",
  "dependency",
  "version control",
  "commit",
  "branch",
  "merge",
  "pull request",
  "conflict",
  "repository",
  "remote",
  "local",
  "clone",
  "push",
  "pull",
  "fetch",
  "stash",
  "rebase",
  "cherry-pick",
  "bisect",
  "revert",
  "reset",
  "log",
  "status",
  "diff",
  "patch",
  "fork",
  "open source",
  "license",
  "community",
  "contribute",
  "collaborate",
  "opensource",
  "software",
  "application",
  "website",
  "app",
  "game",
  "tool",
  "utility",
  "library",
  "framework",
  "api",
  "service",
  "platform",
  "ecosystem",
  "stack",
  "technology",
  "innovation",
  "problem-solving",
  "creativity",
  "learning",
  "growth",
  "career",
  "job",
  "opportunity",
  "future",
  "success",
  "passion",
  "enjoyment",
  "typescript",
  "rust",
  "go",
  "kotlin",
  "swift",
  "ruby",
  "php",
  "perl",
  "assembly",
  "lisp",
  "haskell",
  "scala",
  "clojure",
  "erlang",
  "elixir",
  "dart",
  "flutter",
  "cordova",
  "ionic",
  "electron",
  "webpack",
  "babel",
  "gulp",
  "grunt",
  "npm",
  "yarn",
  "pnpm",
  "jest",
  "mocha",
  "chai",
  "selenium",
  "cypress",
  "puppeteer",
  "playwright",
  "rest api",
  "graphql",
  "json",
  "xml",
  "yaml",
  "csv",
  "regex",
  "algorithm",
  "data structure",
  "linked list",
  "stack",
  "queue",
  "tree",
  "graph",
  "hash table",
  "heap",
  "sort",
  "search",
  "dynamic programming",
  "greedy algorithm",
  "divide and conquer",
  "backtracking",
  "branch and bound",
  "graph algorithms",
  "shortest path",
  "minimum spanning tree",
  "max flow",
  "linear programming",
  "machine learning",
  "deep learning",
  "neural network",
  "artificial intelligence",
  "data science",
  "big data",
  "cloud computing",
  "serverless",
  "microservices",
  "containerization",
  "virtualization",
  "iot",
  "blockchain",
  "cryptocurrency",
  "cybersecurity",
  "penetration testing",
  "ethical hacking",
  "information security",
  "network security",
  "web security",
  "application security",
  "data security",
  "privacy",
  "compliance",
  "regulation",
  "gdpr",
  "ccpa",
  "accessibility",
  "inclusivity",
  "diversity",
  "equity",
  "bias",
  "ethics",
  "sustainability",
  "climate change",
  "social impact",
  "open source",
  "license",
  "community",
  "contribute",
  "collaborate",
  "opensource",
  "software",
  "application",
  "website",
  "app",
  "game",
  "tool",
  "utility",
  "library",
  "framework",
  "api",
  "service",
  "platform",
  "ecosystem",
  "stack",
  "technology",
  "innovation",
  "problem-solving",
  "creativity",
  "learning",
  "growth",
  "career",
  "job",
  "opportunity",
  "future",
  "success",
  "passion",
  "enjoyment",
  "design",
  "user experience",
  "user interface",
  "product design",
  "interaction design",
  "visual design",
  "prototyping",
  "wireframing",
  "mockup",
  "testing",
  "usability",
  "accessibility",
  "a11y",
  "inclusive design",
  "agile",
  "scrum",
  "kanban",
  "waterfall",
  "devops",
  "cicd",
  "continuous delivery",
  "continuous deployment",
  "infrastructure as code",
  "automation",
  "cloud",
  "aws",
  "gcp",
  "azure",
  "docker",
  "kubernetes",
  "serverless",
  "microservices",
  "containerization",
  "virtualization",
  "iot",
  "blockchain",
  "cryptocurrency",
  "cybersecurity",
  "penetration testing",
  "ethical hacking",
  "information security",
  "network security",
  "web security",
  "application security",
  "data security",
  "privacy",
  "compliance",
  "regulation",
  "gdpr",
  "ccpa",
  "accessibility",
  "inclusivity",
  "diversity",
  "equity",
  "bias",
  "ethics",
  "sustainability",
  "climate change",
  "social impact",
  "open source",
  "license",
  "community",
  "contribute",
  "collaborate",
  "opensource",
  "software",
  "application",
  "website",
  "app",
  "game",
  "tool",
  "utility",
  "library",
  "framework",
  "api",
  "service",
  "platform",
  "ecosystem",
  "stack",
  "technology",
  "innovation",
  "problem-solving",
  "creativity",
  "learning",
  "growth",
  "career",
  "job",
  "opportunity",
  "future",
  "success",
  "passion",
  "enjoyment",
];